services:
 postgres-db:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_DB=transactions_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"

